CREATE SCHEMA IF NOT EXISTS TVAUC12;
USE TVAUC12;
CREATE TABLE IF NOT EXISTS TAREFAS(
  TAR_ID SMALLINT PRIMARY KEY AUTO_INCREMENT,
  TAR_TITULO CHAR(100) NOT NULL,
  TAR_DS TEXT,
  TAR_DT_CONCLUSAO DATETIME DEFAULT NULL,
  TAR_PRIORIDADE ENUM('Baixa' , 'Media', 'Alta') NOT NULL	
);